FROM php:8.0-cli
RUN apt-get update && apt-get install -y libpq-dev unzip git
RUN docker-php-ext-install -j$(nproc) pgsql
RUN docker-php-ext-enable pgsql
#RUN pecl install --soft --force xdebug-3.1.3
#RUN docker-php-ext-enable xdebug
#COPY ./php.d/xdebug.ini /usr/local/etc/php/conf.d/xdebug.ini
COPY ./composer.phar /usr/local/bin/composer
RUN chmod +x /usr/local/bin/composer
