services:
    # Message broker SQL queries are simple and supposedly safe and will
    # hopefully not trigger any contention, changing its SQL connection is
    # probably unnecessary and will possibility lead to wrongly sent message
    # issued by business transactions which have been ROLLBACK.
    goat.runner.message_broker:
        alias: "goat.runner.default"

    message_broker.message_consumer_factory.goat_query:
        public: false
        class: MakinaCorpus\MessageBroker\Adapter\GoatQuery\GoatQueryMessageConsumerFactory
        arguments: ["@goat.runner.message_broker", "@normalization.serializer"]
        tags: [{ name: "monolog.logger", channel: "message_broker" }]
        calls:
            - [setNameMap, ["@normalization.name_map"]]

    message_broker.consumer_factory:
        alias: message_broker.message_consumer_factory.goat_query

    MakinaCorpus\MessageBroker\MessageConsumerFactory:
        alias: message_broker.consumer_factory

    message_broker.message_publisher.goat_query:
        public: false
        class: MakinaCorpus\MessageBroker\Adapter\GoatQuery\GoatQueryMessagePublisher
        arguments: ["@goat.runner.message_broker", "@normalization.serializer"]
        tags: [{ name: "monolog.logger", channel: "message_broker" }]
        calls:
            - [setNameMap, ["@normalization.name_map"]]

    message_broker.publisher:
        alias: message_broker.message_publisher.goat_query

    MakinaCorpus\MessageBroker\MessagePublisher:
        alias: message_broker.publisher
